//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobWindowNew.API.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantApstream
    {
        public long Id { get; set; }
        public long listingID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime date { get; set; }
        public int SchedulingPod { get; set; }
        public string File { get; set; }
        public string listingTitle { get; set; }
        public int OfficeId { get; set; }
        public Nullable<int> specificSourceID { get; set; }
        public string specificSourceName { get; set; }
    }
}
